# Generated by Django 2.2 on 2020-02-16 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50, verbose_name='Clients First Name')),
                ('address', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Address')),
                ('city', models.CharField(default=' ', max_length=50, verbose_name='City')),
                ('state', models.CharField(default='NE', max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(default='00000', max_length=10, verbose_name='Zip Code')),
                ('email', models.EmailField(default=' ', max_length=100, verbose_name='E-mail')),
                ('cell_phone', models.CharField(default='(402)000-0000', max_length=50, verbose_name='Cell')),
                ('acct_number', models.CharField(blank=True, default='00000', max_length=50, null=True, verbose_name='Account Number')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='cardio', max_length=26, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='running', max_length=26, unique=True)),
                ('exercise_category_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ExerciseCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('duration', models.IntegerField(default='10')),
                ('duration_units', models.CharField(default='min', max_length=5)),
                ('reps', models.IntegerField(default='10')),
                ('weight', models.IntegerField(default='10')),
                ('weight_units', models.CharField(default='lbs', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Exercises')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.Client')),
            ],
        ),
    ]
