# Generated by Django 2.2 on 2020-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='diary',
            name='day',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
