# Generated by Django 2.2 on 2020-02-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='cardio', max_length=26, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='running', max_length=5, unique=True)),
                ('exercise_category_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.exercise_category')),
            ],
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default='10', max_length=50)),
                ('duration_units', models.CharField(default='min', max_length=5)),
                ('reps', models.IntegerField(default='10', max_length=50)),
                ('weight', models.IntegerField(default='10', max_length=50)),
                ('weight_units', models.CharField(default='lbs', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.exercises')),
            ],
        ),
    ]
