# Generated by Django 2.2 on 2020-02-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200216_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='trainer',
        ),
    ]
