# Generated by Django 2.2 on 2020-02-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_diary_exercise_category_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='duration',
            field=models.IntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='reps',
            field=models.IntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weight',
            field=models.IntegerField(default='10'),
        ),
    ]
