# Generated by Django 2.2 on 2020-02-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200212_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exercise_category',
            new_name='exerciseCategory',
        ),
    ]
