# Generated by Django 2.2 on 2020-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200212_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(default='running', max_length=26, unique=True),
        ),
    ]
