# Generated by Django 2.2 on 2020-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200216_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='day',
            field=models.DateField(default='2020-02-16'),
            preserve_default=False,
        ),
    ]
