# Generated by Django 2.2 on 2020-02-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_comment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
    ]
