# Generated by Django 2.2 on 2020-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
