# Generated by Django 2.2 on 2020-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200309_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='day',
            field=models.DateField(),
        ),
    ]
