# Generated by Django 2.2 on 2020-03-10 04:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20200309_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
