# Generated by Django 2.2 on 2020-02-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200212_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
