# Generated by Django 2.2 on 2020-03-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200309_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(default='(402)000-0000', max_length=50, verbose_name='Cell'),
        ),
    ]
