# Generated by Django 2.2 on 2020-02-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200212_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='acct_number',
            field=models.CharField(blank=True, default='00000', max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(default='(402)000-0000', max_length=50, verbose_name='Cell'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default=' ', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default=' ', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Clients First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(default='NE', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(default='00000', max_length=10, verbose_name='Zip Code'),
        ),
    ]
